/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import connection.koneksi;
import data.Users;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import view.user.U_Absensi;
import view.user.U_Home;

/**
 *
 * @author adity
 */
public class Login extends javax.swing.JFrame {

    private final Connection kon = new koneksi().connect();
    private Statement st;
    public ResultSet rslogin;
    private String user, pass, name;
    private int role;
    private String query = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public void login() {
        if (jT_user.getText().trim().isEmpty() && jP_pass.getText().trim().isEmpty()) {
            jT_user.setText("masukkan username anda");
            jP_pass.setText("masukkan password anda");
        } else if (jT_user.getText().trim().isEmpty()) {
            jT_user.setText("masukkan username anda");
        } else if (jP_pass.getText().trim().isEmpty()) {
            jP_pass.setText("masukkan password anda");
        } else {
            user = String.valueOf(jT_user.getText());
            pass = String.valueOf(jP_pass.getText());
            jT_user.requestFocus();

            try {
                query = "SELECT * FROM users WHERE username ='" + user + "' AND password= '" + pass + "'";
                st = kon.createStatement();
                rslogin = st.executeQuery(query);

                if (rslogin.next()) {
                    role = rslogin.getInt("role");
                    if (role == 1) {
                        name = rslogin.getString("name");
                        Users users = new Users(user, pass, name);
                        Home home = new Home(users);
                        JOptionPane.showMessageDialog(null, "Login Berhasil \nSelamat Datang \t" + name);
                        home.setVisible(true);
                        dispose();
                    } else if (role == 2) {
                        name = rslogin.getString("name");
                        Users users = new Users(user, pass, name);
                        U_Home home = new U_Home(users);
                        JOptionPane.showMessageDialog(null, "Login Berhasil \nSelamat Datang \t" + name);
                        home.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Login Gagal \nUsername \t" + user + " tidak memiliki Role");
                        jT_user.setText("");
                        jP_pass.setText("");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Username Atau Password Salah");
                    jT_user.setText("");
                    jP_pass.setText("");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    void cekpass() {
        if (jC_pass.isSelected()) {
            jP_pass.setEchoChar((char) 0);
            jC_pass.setText("Hide");
        } else {
            jP_pass.setEchoChar('*');
            jC_pass.setText("Show");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_judul1 = new javax.swing.JLabel();
        jL_judul2 = new javax.swing.JLabel();
        jT_user = new javax.swing.JTextField();
        jP_pass = new javax.swing.JPasswordField();
        jL_user = new javax.swing.JLabel();
        jL_pass = new javax.swing.JLabel();
        jB_login = new javax.swing.JButton();
        jB_pass = new javax.swing.JButton();
        jC_pass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_judul1.setText("SELAMAT DATANG");

        jL_judul2.setText("APLIKASI KEPEGAWAIAN");

        jT_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_userActionPerformed(evt);
            }
        });

        jL_user.setText("username");

        jL_pass.setText("password");

        jB_login.setText("Login");
        jB_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_loginActionPerformed(evt);
            }
        });

        jB_pass.setText("Register");
        jB_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_passActionPerformed(evt);
            }
        });

        jC_pass.setText("Show");
        jC_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_pass))
                    .addComponent(jL_judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_user, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jP_pass)
                            .addComponent(jT_user, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jL_judul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_judul2)
                .addGap(29, 29, 29)
                .addComponent(jL_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jT_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jL_pass)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jP_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_pass))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_login)
                    .addComponent(jB_pass))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jT_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_userActionPerformed

    private void jB_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_loginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_jB_loginActionPerformed

    private void jC_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_passActionPerformed
        // TODO add your handling code here:
        cekpass();
    }//GEN-LAST:event_jC_passActionPerformed

    private void jB_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_passActionPerformed
        // TODO add your handling code here:
        new Regis().setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_login;
    private javax.swing.JButton jB_pass;
    private javax.swing.JCheckBox jC_pass;
    private javax.swing.JLabel jL_judul1;
    private javax.swing.JLabel jL_judul2;
    private javax.swing.JLabel jL_pass;
    private javax.swing.JLabel jL_user;
    private javax.swing.JPasswordField jP_pass;
    private javax.swing.JTextField jT_user;
    // End of variables declaration//GEN-END:variables
}
